/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbs;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author alroy
 */
public class ASM extends javax.swing.JFrame {
    static Connection connection;
    /**
     * Creates new form ASM
     */
    public ASM() {
        initComponents();
        try {
            connection =MysqlConnect.dbConnnector();
            DatabaseMetaData meta = connection.getMetaData();
            String[] types = {"TABLE"};
            ResultSet tables = meta.getTables(null, null, "asm", types);
            String query;
            PreparedStatement pst;
            ResultSet rs1;
            if (tables.next()) {
                // Table exists
            }
            else {
                // Table does not exist
                System.out.println("Table does not exist Creating new Table");
                Statement stmt = connection.createStatement();
                query= "CREATE TABLE asm "+
                "(Allocate_id INTEGER NOT Null AUTO_INCREMENT,"+
                "Movie VARCHAR(45) NOT NULL,"+
                "Date VARCHAR(45) NOT NULL,"+
                "Time VARCHAR(45) NOT NULL,"+
                "Screen VARCHAR(20) NOT NULL,"+
                "Rate INTEGER NOT NULL,"+
                "PRIMARY KEY(Allocate_id))";
                stmt.executeUpdate(query);
                System.out.println("created table asm");
             }
            query="select * from asm";
            pst=connection.prepareStatement(query);
            rs1=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            pst.close();
            rs1.close();
            connection.close();
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        start_hr = new javax.swing.JSpinner();
        start_min = new javax.swing.JSpinner();
        start_sec = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        end_hr = new javax.swing.JSpinner();
        end_min = new javax.swing.JSpinner();
        end_sec = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Allocate Screen");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setText("Movie Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 90, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(100, 20, 90, 20);

        jButton1.setText("Search");
        jPanel2.add(jButton1);
        jButton1.setBounds(230, 20, 65, 23);

        jLabel3.setText("Date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 50, 14);
        jPanel2.add(jXDatePicker1);
        jXDatePicker1.setBounds(80, 70, 114, 22);
        jPanel2.add(jXDatePicker2);
        jXDatePicker2.setBounds(240, 70, 114, 22);

        jLabel4.setText("to");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 70, 34, 14);

        jLabel5.setText("Time");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 50, 14);

        start_hr.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(24.0f), Float.valueOf(1.0f)));
        jPanel2.add(start_hr);
        start_hr.setBounds(50, 120, 50, 30);

        start_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel2.add(start_min);
        start_min.setBounds(100, 120, 50, 30);

        start_sec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel2.add(start_sec);
        start_sec.setBounds(150, 120, 50, 30);

        jLabel6.setText("to");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(210, 120, 10, 14);

        end_hr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        jPanel2.add(end_hr);
        end_hr.setBounds(220, 120, 50, 30);

        end_min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel2.add(end_min);
        end_min.setBounds(270, 120, 50, 30);

        end_sec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel2.add(end_sec);
        end_sec.setBounds(320, 120, 50, 30);

        jLabel7.setText("Choose Screen");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 160, 120, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(120, 160, 110, 20);

        jLabel8.setText("Rate");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 210, 50, 14);
        jPanel2.add(rate);
        rate.setBounds(120, 210, 70, 0);

        jButton2.setText("Allocate");
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 250, 100, 23);

        jButton3.setText("Update");
        jPanel2.add(jButton3);
        jButton3.setBounds(120, 290, 100, 23);

        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(380, 10, 710, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner end_hr;
    private javax.swing.JSpinner end_min;
    private javax.swing.JSpinner end_sec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel rate;
    private javax.swing.JSpinner start_hr;
    private javax.swing.JSpinner start_min;
    private javax.swing.JSpinner start_sec;
    // End of variables declaration//GEN-END:variables
}
